name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Replace secrets in Secrets.kt
        run: |
          cp app/src/main/java/luph/vulcanizerv3/updates/data/sectrets.kt.tmp app/src/main/java/luph/vulcanizerv3/updates/data/sectrets.kt
          sed -i "s|val TELEGRAM_BOT_API = \"\"|val TELEGRAM_BOT_API = \"${{ secrets.TELEGRAM_BOT_TOKEN }}\"|" app/src/main/java/luph/vulcanizerv3/updates/data/sectrets.kt
          sed -i "s|val TELEGRAM_FEEDBACK_CHANNEL = \"\"|val TELEGRAM_FEEDBACK_CHANNEL = \"${{ secrets.TELEGRAM_FEEDBACK_CHANNEL }}\"|" app/src/main/java/luph/vulcanizerv3/updates/data/sectrets.kt

      - name: Build with Gradle (Debug)
        run: ./gradlew assembleDebug

      - name: Get Firebase secret
        run: |
          echo "${{ secrets.FIREBASE_JSON }}" > firebase.json
          chmod 777 firebase.json

      - name: Cloning Data Repo
        run: git clone https://huggingface.co/datasets/Luphaestus/VulcanUpdates3Data

      - name: asdadasd
        run: |
          ls VulcanUpdates3Data
          ls VulcanUpdates3Data/core
          ls VulcanUpdates3Data/Vulcan-Updates

      - name: Copy build into data Repo
        run: cp -r app/build/outputs/apk/debug/app-debug.apk VulcanUpdates3Data/core/Vulcan-Updates/file

      - name: Commit and push
        run: |
          python VulcanUpdates3Data/scripts/updateGithub.py
