name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Rename Secretes
        run: mv app/src/main/java/luph/vulcanizerv3/updates/data/sectrets.kt.tmp app/src/main/java/luph/vulcanizerv3/updates/data/sectrets.kt

      - name: Build with Gradle (Debug)
        run: ./gradlew assembleDebug
